### ISSUE TITLE
Improve the "pluie" slash command

### ISSUE THREAD

**Issue by clement-pages** [skyeye-weather/sunbot#41]
# Task description

The purpose of this task is to upgrade the `pluie` slash command

# Validation criteria
* [x] Convert this command to a slash command
* [ ] Replace the current embed response with an image or a graph
* [ ] Test the improvement on Discord
