### ISSUE TITLE
Improve the handling of weather API requests

### ISSUE THREAD

**Issue by clement-pages** [skyeye-weather/sunbot#43]
# Task description

For now, the weather API handler just generates a request to the API and returns the response as a dictionary, without any modification to the data.  The handler just prevents the user with log messages when the request failed. The purpose of this task is to improve the management of the response with the aim to improve the robustness of the bot to modification in the structure of returned JSON response. This is also the opportunity to fix style issue and to improve the code.

# Validation criteria
* [x] Create dictionary(ies) from response data to only keep needed data in a standard format for all Sunbot modules
* [x] Adapt programs that use the current API handler structure
* [x] Test the new structure(s)
* [x] #69
