### ISSUE TITLE
Create weather alert handler

### ISSUE THREAD

**Issue by clement-pages** [skyeye-weather/sunbot#44]
# Task description

A new feature of the Sunrise version is to alert the user when a weather alert is triggered by Meteo France (the national weather service in France). In a first time, to do that, the bot will send a webhook message to all discord servers that have enabled these features. This webhook will contain information about the thrown weather alerts such as level and type alert. For now, this new feature will be only available to the Haute-Garonne department.

# Validation criteria
* [x] Create a user account on Meteo France API service
* [x] Get a token in order to use Meteo France API
* [x] #90
* [ ] #91
* [ ] #92
* [ ] Implement ~~webhook~~ message generation and handle its sending on discord when an alert is triggered

# Useful links

* [meteo france dev portal](https://portail-api.meteofrance.fr/devportal/)
* [meteo france public data portal](https://donneespubliques.meteofrance.fr/)
