### ISSUE TITLE
Handle send of daily weather for all timezones

### ISSUE THREAD

**Issue by clement-pages** [skyeye-weather/sunbot#57]
## Task description

Currently,  hour events are hard coded in the program, namely for daily weather event. Thus, developer have to manually switch from winter to summer hour and inversely. This is not convenient and need to deploy a new version for the bot each time.  A solution is to automatically handle this point in the code.

## Validation criteria

* [x] : Find a way to automatically switch between summer and winter hours
* [x] : Handle all timezones for daily weather feature
* [x] : Implement this solution in the code
* [x] : Test and validate the implementation
